image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  branches:
    Production_Tests:
      - step:
          name: Build and UnitTests
          caches:
            - dotnetcore
          script:
            - cd PrestarTest
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet test --no-build --configuration Release 
            - cd ..
      - step:
          name: Build and IntegrationTests
          caches:
            - dotnetcore
          script:
            - cd IntegrationTest
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet test --no-build --configuration Release 
            - cd ..
            
      - step:
          name: Deployment
          image: docker:latest
          services:
            - docker
          script:
            - cd Prestar
            - touch imageid.txt
            - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/prestar/my-app .
            - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
            - docker push registry.heroku.com/prestar/my-app
            - apk add --no-cache curl
            - echo "Docker Image ID is $(cat imageid.txt)"
            - |-
              curl -X PATCH https://api.heroku.com/apps/prestar/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_API_KEY}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
            - cd ..

definitions:
  services:
    docker:
      memory: 2048